version: '3.9'

services:
  proxy:
    image: nginx
    container_name: proxy
    extra_hosts:
      - 'host.docker.internal,stats.devel.place,visualizer.devel.place,explorer.devel.place:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
    env_file:
      - ../envs/common-proxy.env
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    ports:
      - target: 80
        published: 80
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081
