version: '3.9'

services:
  block_proxy:
    image: nginx
    container_name: block_proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://block_backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://block_frontend:3000}
    ports:
      - target: 80
        published: 80
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081
