services:
  proxy:
    image: nginx
    container_name: proxy
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy/default.conf.template:/etc/nginx/templates/default.conf.template"
      - "../proxy/microservices.conf.template:/etc/nginx/templates/microservices.conf.template"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    ports:
      - target: 80
        published: ${EXTERNAL_PORT}
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081
